import React from 'react';
import {View, StyleSheet, ScrollView, Text} from 'react-native';
import BlueButton from '../../components/moleculs/blueButton';
import HeaderPages from '../../components/moleculs/headerPages';
import { Dimensions } from 'react-native';
import { useTranslation } from 'react-i18next';
const {width, height} = Dimensions.get('window');

const TermsAndConditions = ({navigation}) => {
  const {t, i18n}=useTranslation()
  return (
    <View style={styles.Container}>
      <HeaderPages
        hideShowTitle={true}
        value={'Terms and conditions'}
        onPress={() => navigation.goBack()}
      />
      <ScrollView style={styles.ContainerBody}>
        <View style={{flexDirection: 'row'}}>
          <Text style={styles.TextTitleNumber}>A</Text>
          <Text style={styles.TextTitle}>{t('Terms')}</Text>
        </View>
        <View style={{flexDirection: 'row'}}>
          <Text style={styles.TextNumber}>1</Text>
          <Text style={styles.TextDescription}>
            {t('TransEvilz (Mobile Banking) is a banking product service')}
            {t('TransEvilz which can be accessed directly by the Customer via cell phone/cellphone, either by using the menu that is already available on the Subscriber Identification Module (SIM) Card, by using SMS media or using the menu on TransEvilz mobile by using the internet network media on the cellphone combined with media SMS according to the provisions that apply at TransEvilz.')}
          </Text>
        </View>
        <View style={{flexDirection: 'row'}}>
          <Text style={styles.TextNumber}>2</Text>
          <Text style={styles.TextDescription}>
            {t(`TransEvilz mobile is an application that can be downloaded from the official TransEvilz website as well as the official application/software distribution media designated by TransEvilz which is owned by the mobile operating system located on the customer's cellphone to make transactions through TransEvilz or to obtain TransEvilz info.`)}
          </Text>
        </View>
        <View style={{flexDirection: 'row'}}>
          <Text style={styles.TextNumber}>3</Text>
          <Text style={styles.TextDescription}>
            {t('Evilz PIN (Personal Identification Number) is a personal identification number for Customers who use TransEvilz.')}
          </Text>
        </View>
        <View style={{flexDirection: 'row'}}>
          <Text style={styles.TextNumber}>4</Text>
          <Text style={styles.TextDescription}>
            {t('Access Code is a personal code for Customers who use TransEvilz on TransEvilz mobile.')}
          </Text>
        </View>
        <View style={{flexDirection: 'row'}}>
          <Text style={styles.TextNumber}>5</Text>
          <Text style={styles.TextDescription}>
            {t('Transaction Code is a code generated by TransEvilz on TransEvilz mobile to make cash withdrawal transactions, cash deposits at TransEvilz ATMs, or transactions at TransEvilz branch offices without using a TransEvilz Card.')}
          </Text>
        </View>
        <View style={{flexDirection: 'row'}}>
          <Text style={styles.TextNumber}>6</Text>
          <Text style={styles.TextDescription}>
            {t('TransEvilz Credit Card is any type of credit card issued by TransEvilz for the Customer.')}
          </Text>
        </View>
        <View style={{flexDirection: 'row'}}>
          <Text style={styles.TextNumber}>7</Text>
          <Text style={styles.TextDescription}>
            {t('TransEvilz which can be accessed by customers via smartphones.')}
          </Text>
        </View>
        <View style={{flexDirection: 'row'}}>
          <Text style={styles.TextNumber}>8</Text>
          <Text style={styles.TextDescription}>
            {t('TransEvilz is an information service regarding TransEvilz products and services and their promotional programs, locations of TransEvilz Automated Teller Machines (ATMs) and BCA branch offices, as well as other information related to TransEvilz.')}
          </Text>
        </View>
        <View style={{flexDirection: 'row'}}>
          <Text style={styles.TextNumber}>9</Text>
          <Text style={styles.TextDescription}>
            {t('Sakuku is electronic money denominated in Rupiah using the official application from TransEvilz and server-based and using a cell phone number as an account number.')}
          </Text>
        </View>
        <View style={{flexDirection: 'row'}}>
          <Text style={styles.TextNumber}>10</Text>
          <Text style={styles.TextDescription}>
            {t('TransEvilz Card is an ATM card issued by BCA which can be used by TransEvilz Cardholders to make certain banking transactions through TransEvilz and/or other means determined by TransEvilz.')}
          </Text>
        </View>
        <View style={{flexDirection: 'row'}}>
          <Text style={styles.TextTitleNumber}>B</Text>
          <Text style={styles.TextTitle}>{t('Conditions')}</Text>
        </View>
        <View style={{flexDirection: 'row'}}>
          <Text style={styles.TextNumber}>1</Text>
          <Text style={styles.TextDescription}>
            {t('TransEvilz (Mobile Banking) is a banking product service')}
            {t('TransEvilz which can be accessed directly by the Customer via cell phone/cellphone, either by using the menu that is already available on the Subscriber Identification Module (SIM) Card, by using SMS media or using the menu on TransEvilz mobile by using the internet network media on the cellphone combined with media SMS according to the provisions that apply at TransEvilz.')}
          </Text>
        </View>
        <View style={{flexDirection: 'row'}}>
          <Text style={styles.TextNumber}>2</Text>
          <Text style={styles.TextDescription}>
            {t(`TransEvilz mobile is an application that can be downloaded from the official TransEvilz website as well as the official application/software distribution media designated by TransEvilz which is owned by the mobile operating system located on the customer's cellphone to make transactions through TransEvilz or to obtain TransEvilz info.`)}
          </Text>
        </View>
        <View style={{flexDirection: 'row'}}>
          <Text style={styles.TextNumber}>3</Text>
          <Text style={styles.TextDescription}>
            {t('Evilz PIN (Personal Identification Number) is a personal identification number for Customers who use TransEvilz.')}
          </Text>
        </View>
        <View style={{flexDirection: 'row'}}>
          <Text style={styles.TextNumber}>4</Text>
          <Text style={styles.TextDescription}>
            {t('Access Code is a personal code for Customers who use TransEvilz on TransEvilz mobile.')}
          </Text>
        </View>
        <View style={{flexDirection: 'row'}}>
          <Text style={styles.TextNumber}>5</Text>
          <Text style={styles.TextDescription}>
            {t('Transaction Code is a code generated by TransEvilz on TransEvilz mobile to make cash withdrawal transactions, cash deposits at TransEvilz ATMs, or transactions at TransEvilz branch offices without using a TransEvilz Card.')}
          </Text>
        </View>
        <View style={{height: 50}} />
      </ScrollView>
      <View style={styles.ButtonLanjut}>
        <BlueButton
          value={'Yes I understand'}
          onPress={() => navigation.goBack()}
          isButton={true}
        />
      </View>
    </View>
  );
};

export default TermsAndConditions;
const styles = StyleSheet.create({
  Container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  ContainerBody: {
    backgroundColor: '#F1F7FF',
    width: '90%',
    alignSelf: 'center',
    paddingTop: 10,
    marginTop: 15,
  },
  TextTitle: {
    fontWeight: '700',
    paddingTop: 20,
  },
  TextTitleNumber: {
    fontWeight: '700',
    marginRight: 10,
    paddingTop: 20,
  },
  TextNumber: {
    textAlign: 'center',
    width: '5%',
  },
  ButtonLanjut: {
    width: '90%',
    marginTop: 20,
    alignSelf: 'center',
  },
  TextDescription:{
    paddingRight:20
  }
});
